server:
  port: 8080

spring:
  resources:
    chain:
      enabled: true

spring.datasource:
  url: jdbc:mysql://localhost:3306/event-organiser
  username: johny
  password: johny

spring.jpa:
  hibernate:
    ddl-auto: create